name: Test

on:
    push:
    pull_request:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 15.x
            - name: Install JS testing dependencies
              run: npm ci
            - name: Install Playwright dependencies
              run: npx playwright install-deps
            - name: Install browsers
              run: npx playwright install
            - name: Run tests
              run: npx playwright test

